- name: Helm download and install
  shell: export HELM_URL=https://get.helm.sh/helm-v3.8.0-rc.2-linux-amd64.tar.gz && curl "$HELM_URL" | tar --strip-components 1 -C /usr/local/bin -zxf -

- name: Add permissions to helm binary
  file:
    path: /usr/local/bin/helm
    mode: u+rwx,g+rx,o+rx

- name: Create soft link for helm command
  file:
    src: /usr/local/bin/helm
    dst: /usr/bin/helm
    state: link

- name: Create Helm namespace
  shell: kubectl create ns helm

- name: Helm init
  shell: helm repo add bitnami https://charts.bitnami.com/bitnami

