- name: Create nameSpace prometheus
  command: kubectl create ns prometheus

- name: Add repo prometheus-community 
  shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: Helm install kube-prometheus-stack
  shell: helm install prometheus prometheus-community/kube-prometheus-stack -n prometheus
