- name: Install Docker-CE engine
  yum: 
    name: docker-ce-{{ docker_version }}
    state: installed
    enablerepo: docker-ce  

- name: Configure additional engine options
  copy:
    content: "{{ docker_ce_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_ce_daemon_options is defined

- name: Enable docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes
